spring.application.name=law-firm-website
server.port=8080
spring.mail.host=smtp.protonmail.com
spring.mail.port=587
spring.mail.username=BarristerLawFirm92@protonmail.com
spring.mail.password=YOUR_EMAIL_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.starttls.class=javax.net.ssl.SSLSocketFactory
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false